### ISSUE TITLE
Amazing app,very minor bugs

### ISSUE THREAD

**Issue by eiidoubleyuwes** [IamMuuo/academia#55]
1.The app look and feel is spot on,however I have noticed a small glitch where the first time I logged into the app it showed semester 1% complet,however upon opening it today it shows 100% complete.
This is a very minor issue,I just wanted to bring it to the attention of the devs. Otherwise this is an app I see myself using for as long as I am in school.Below attached find the screenshot:
![Screenshot_20240203-233328](https://github.com/IamMuuo/academia/assets/148796574/f42b91cc-2e8e-4e07-8b4b-5f7e3170c80b)

2.Just asking,does the Catering token work??

**Comment by eiidoubleyuwes** [comment]
Also,minor request,on the courses tab,can the courses appear in terms of day the class is in sequentially ie Monday, ACS 303,Tuesday unit ACS 302 as opposed to the unit codes being arranged in order of lowest to highest ie what it is now ACS302 -Tuesday,ACS 303 - Monday.

Just to make it easier to understand the timetable

**Comment by IamMuuo** [comment]
> 1.The app look and feel is spot on,however I have noticed a small glitch where the first time I logged into the app it showed semester 1% complet,however upon opening it today it shows 100% complete. This is a very minor issue,I just wanted to bring it to the attention of the devs. Otherwise this is an app I see myself using for as long as I am in school.Below attached find the screenshot: ![Screenshot_20240203-233328](https://private-user-images.githubusercontent.com/148796574/302061525-f42b91cc-2e8e-4e07-8b4b-5f7e3170c80b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMzIyMjEsIm5iZiI6MTcwNzAzMTkyMSwicGF0aCI6Ii8xNDg3OTY1NzQvMzAyMDYxNTI1LWY0MmI5MWNjLTJlOGUtNGUwNy04YjRiLTVmN2UzMTcwYzgwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQwNzMyMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmY2MzU2ZDhiZGVmYmU0Y2Y4NjUzMmE2YWI3YzI2OTBkOWEyZTliN2I1ZDNhOTUxODYwNzgzNDY4MjljM2IzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dE9bEZh3QlWl3LMk4IUloR4KZtxtRrVbOlotR4ylBPM)
> 
> 2.Just asking,does the Catering token work??

# Issue address
- As for the semester issue there was a push last week that addressed the issue therefore consider it resolved.
- For the catering token, yes it does work as intended.

**Comment by IamMuuo** [comment]
> Also,minor request,on the courses tab,can the courses appear in terms of day the class is in sequentially ie Monday, ACS 303,Tuesday unit ACS 302 as opposed to the unit codes being arranged in order of lowest to highest ie what it is now ACS302 -Tuesday,ACS 303 - Monday.
> 
> Just to make it easier to understand the timetable

# Issue address
- Yes this is to our attention and plans are underway to address this problem
- Perhaps keep watch on the next merge to main it will be addressed
